# Generated by Django 5.1.6 on 2025-03-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instruxtor',
            new_name='instructor',
        ),
    ]
